import { GOV_SLUGS, TECH_SLUGS } from "@/lib/content-keys";
import { GOV_OFFERINGS } from "@/lib/gov-offerings";
import type { SearchNode } from "./types";

function offeringHref(category: keyof typeof GOV_SLUGS, slug: string) {
  return `/services/government/${GOV_SLUGS[category]}/${slug}`;
}

function categoryHref(category: keyof typeof GOV_SLUGS) {
  return `/services/government/${GOV_SLUGS[category]}`;
}

/**
 * Search Intelligence catalog — hubs, aliases, relations.
 * Aliases include dialect, typos, English, Roman Urdu. Not invented official fees/rules.
 */
export const SEARCH_CATALOG: SearchNode[] = [
  // —— Pillars ——
  {
    id: "pillar-gov",
    kind: "pillar",
    i18nKey: "gov",
    href: "/services/government",
    hubs: ["معاملة", "حكومي", "تعقيب"],
    aliases: [
      "خدمات حكومية",
      "معاملات حكومية",
      "تعقيب",
      "معقب",
      "مكتب تعقيب",
      "government services",
      "tasami government",
    ],
    priority: 40,
    tier: "A",
  },
  {
    id: "pillar-tech",
    kind: "pillar",
    i18nKey: "tech",
    href: "/services/tech",
    hubs: ["تقني", "موقع", "تطبيق"],
    aliases: ["خدمات تقنية", "تقنية", "tech services", "digital"],
    priority: 35,
    tier: "B",
  },
  {
    id: "pillar-sectors",
    kind: "pillar",
    i18nKey: "sectors",
    href: "/sectors",
    hubs: ["قطاع", "منشأة"],
    aliases: ["قطاعات", "قطاعات أعمال", "sectors"],
    priority: 30,
    tier: "B",
  },

  // —— Categories ——
  {
    id: "cat-passports",
    kind: "category",
    i18nKey: "passports",
    href: categoryHref("passports"),
    hubs: ["اقامة", "تاشيرة", "خروج", "ابشر"],
    aliases: [
      "جوازات",
      "اقامة",
      "تاشيرة",
      "ابشر",
      "مقيم",
      "passports",
      "iqama",
      "visa",
    ],
    platforms: ["absher", "muqeem"],
    related: [
      { id: "offering-workerIqamaRenew", strength: "strong" },
      { id: "offering-exitReentryIssue", strength: "strong" },
      { id: "offering-transferSponsorship", strength: "medium" },
    ],
    intents: ["transactional", "status", "urgent"],
    priority: 90,
    tier: "S",
  },
  {
    id: "cat-labor",
    kind: "category",
    i18nKey: "labor",
    href: categoryHref("labor"),
    hubs: ["كفالة", "نقل", "عامل", "قوى", "عقد"],
    aliases: [
      "عمالة",
      "كفالة",
      "نقل كفالة",
      "نقل خدمات",
      "قوى",
      "اجير",
      "مدد",
      "مساند",
      "labor",
      "sponsorship",
      "qiwa",
      "worker transfer",
      "kafala",
      "naql kafala",
    ],
    platforms: ["qiwa", "mudad", "musaned", "ajeer"],
    related: [
      { id: "offering-transferSponsorship", strength: "direct" },
      { id: "offering-changeProfession", strength: "strong" },
      { id: "offering-workVisaPermanent", strength: "strong" },
    ],
    intents: ["transactional", "commercial", "problem"],
    priority: 95,
    tier: "S",
  },
  {
    id: "cat-commerce",
    kind: "category",
    i18nKey: "commerce",
    href: categoryHref("commerce"),
    hubs: ["سجل", "منشأة", "رخصة", "تجارة"],
    aliases: [
      "سجل تجاري",
      "وزارة التجارة",
      "فتح سجل",
      "تجديد سجل",
      "commercial registration",
      "cr",
      "trade name",
    ],
    platforms: ["commerce", "businessCenter"],
    related: [
      { id: "offering-openCr", strength: "direct" },
      { id: "offering-renewCr", strength: "direct" },
      { id: "offering-transferCrOwnership", strength: "strong" },
    ],
    intents: ["transactional", "commercial"],
    priority: 88,
    tier: "S",
  },
  {
    id: "cat-municipal",
    kind: "category",
    i18nKey: "municipal",
    href: categoryHref("municipal"),
    hubs: ["رخصة", "بلدي", "منشأة"],
    aliases: ["بلدية", "بلدي", "رخصة بلدية", "balady", "municipal license"],
    platforms: ["balady"],
    related: [{ id: "offering-municipalLicense", strength: "direct" }],
    priority: 75,
    tier: "A",
  },
  {
    id: "cat-zakat",
    kind: "category",
    i18nKey: "zakat",
    href: categoryHref("zakat"),
    hubs: ["زكاة", "ضريبة"],
    aliases: ["زكاة", "ضريبة", "قيمة مضافة", "vat", "zatca", "zakat"],
    platforms: ["zakat"],
    related: [{ id: "offering-vatFiling", strength: "direct" }],
    priority: 70,
    tier: "A",
  },
  {
    id: "cat-gosi",
    kind: "category",
    i18nKey: "gosi",
    href: categoryHref("gosi"),
    hubs: ["تامين", "موظف"],
    aliases: ["تامينات", "التأمينات الاجتماعية", "gosi", "social insurance"],
    platforms: ["gosi"],
    related: [{ id: "offering-socialInsuranceReg", strength: "direct" }],
    priority: 72,
    tier: "A",
  },
  {
    id: "cat-najiz",
    kind: "category",
    i18nKey: "najiz",
    href: categoryHref("najiz"),
    hubs: ["توثيق", "وكالة", "ناجز"],
    aliases: ["ناجز", "وكالة", "توثيق", "عدلي", "najiz", "power of attorney"],
    platforms: ["najiz"],
    related: [{ id: "offering-najizAppointment", strength: "direct" }],
    priority: 78,
    tier: "A",
  },
  {
    id: "cat-traffic",
    kind: "category",
    i18nKey: "traffic",
    href: categoryHref("traffic"),
    hubs: ["سيارة", "مرور", "نقل"],
    aliases: ["مرور", "رخصة قيادة", "مخالفات", "مركبة", "traffic", "driving"],
    platforms: ["absher"],
    related: [{ id: "offering-trafficAppointment", strength: "direct" }],
    priority: 65,
    tier: "B",
  },
  {
    id: "cat-civilDefense",
    kind: "category",
    i18nKey: "civilDefense",
    href: categoryHref("civilDefense"),
    hubs: ["رخصة", "سلامة"],
    aliases: ["دفاع مدني", "سلامة", "civil defense", "safety license"],
    related: [{ id: "offering-safetyLicense", strength: "direct" }],
    priority: 60,
    tier: "B",
  },
  {
    id: "cat-health",
    kind: "category",
    i18nKey: "health",
    href: categoryHref("health"),
    hubs: ["رخصة", "صحة"],
    aliases: ["صحة", "صحتي", "هيئة الغذاء", "sfda", "health"],
    platforms: ["sehaty"],
    related: [{ id: "offering-sfdaLicense", strength: "direct" }],
    priority: 58,
    tier: "B",
  },
  {
    id: "cat-civilStatus",
    kind: "category",
    i18nKey: "civilStatus",
    href: categoryHref("civilStatus"),
    hubs: ["احوال", "مواطن"],
    aliases: ["احوال مدنية", "جنسية", "حساب المواطن", "civil status"],
    related: [
      { id: "offering-citizenAccount", strength: "strong" },
      { id: "offering-noorRegistration", strength: "medium" },
    ],
    priority: 55,
    tier: "B",
  },
  {
    id: "cat-ejar",
    kind: "category",
    i18nKey: "ejar",
    href: categoryHref("ejar"),
    hubs: ["عقد", "عقار"],
    aliases: ["ايجار", "عقد ايجار", "عقار", "ejar", "lease"],
    platforms: ["ejar"],
    priority: 62,
    tier: "B",
  },
  {
    id: "cat-investment",
    kind: "category",
    i18nKey: "investment",
    href: categoryHref("investment"),
    hubs: ["منشأة", "استثمار"],
    aliases: ["استثمار", "منشآت", "ميسا", "misa", "monshaat", "investment"],
    platforms: ["misa", "monshaat"],
    priority: 60,
    tier: "B",
  },

  // —— High-value offerings (S/A tiers with rich aliases) ——
  {
    id: "offering-transferSponsorship",
    kind: "offering",
    i18nKey: "transferSponsorship",
    href: offeringHref("labor", "naql-kafala"),
    hubs: ["نقل", "كفالة", "عامل"],
    aliases: [
      "نقل كفالة",
      "نقل كفاله",
      "نقل خدمات",
      "نقل خدمات عامل",
      "نقل خدمات وافد",
      "ابغى انقل العامل",
      "ابغى انقل كفالة",
      "كيف انقل كفالة",
      "معقب نقل كفالة",
      "مكتب نقل كفالة",
      "اجراءات نقل الكفالة",
      "شروط نقل الكفالة",
      "متابعة نقل الكفالة",
      "sponsorship transfer",
      "transfer sponsorship",
      "kafala transfer",
      "worker transfer",
      "naql kafala",
      "transfer of services",
      "qiwa transfer",
      "kafala transfer karna",
      "worker transfer sponsorship",
    ],
    platforms: ["qiwa", "absher"],
    related: [
      { id: "offering-changeProfession", strength: "strong" },
      { id: "offering-workerIqamaRenew", strength: "strong" },
      { id: "offering-ajeerContract", strength: "medium" },
      { id: "cat-labor", strength: "contextual" },
    ],
    intents: ["transactional", "commercial", "problem", "requirements"],
    priority: 100,
    tier: "S",
  },
  {
    id: "offering-workerIqamaRenew",
    kind: "offering",
    i18nKey: "workerIqamaRenew",
    href: offeringHref("passports", "tajdid-iqamat-amala"),
    hubs: ["اقامة", "تجديد", "عامل"],
    aliases: [
      "تجديد اقامة",
      "تجديد اقامة عامل",
      "تجديد الاقامة",
      "العامل انتهت اقامته",
      "اقامة منتهية",
      "صلاحية اقامة",
      "iqama renewal",
      "renew iqama",
      "worker iqama renew",
    ],
    platforms: ["absher", "muqeem"],
    related: [
      { id: "offering-driverIqamaRenew", strength: "strong" },
      { id: "offering-exitReentryIssue", strength: "medium" },
      { id: "offering-transferSponsorship", strength: "medium" },
    ],
    intents: ["transactional", "urgent", "status"],
    priority: 98,
    tier: "S",
  },
  {
    id: "offering-driverIqamaRenew",
    kind: "offering",
    i18nKey: "driverIqamaRenew",
    href: offeringHref("passports", "tajdid-iqama-saeq"),
    hubs: ["اقامة", "تجديد"],
    aliases: ["تجديد اقامة سائق", "اقامة سائق", "driver iqama"],
    platforms: ["absher"],
    related: [{ id: "offering-workerIqamaRenew", strength: "strong" }],
    priority: 80,
    tier: "A",
  },
  {
    id: "offering-exitReentryIssue",
    kind: "offering",
    i18nKey: "exitReentryIssue",
    href: offeringHref("passports", "khuroj-wa-awda"),
    hubs: ["خروج", "تاشيرة", "عامل"],
    aliases: [
      "خروج وعودة",
      "اصدار خروج وعودة",
      "ابغى اطلع خروج",
      "تاشيرة خروج وعودة",
      "exit reentry",
      "exit and reentry",
    ],
    platforms: ["absher"],
    related: [
      { id: "offering-exitReentryExtend", strength: "strong" },
      { id: "offering-finalExit", strength: "medium" },
    ],
    intents: ["transactional", "urgent"],
    priority: 92,
    tier: "S",
  },
  {
    id: "offering-exitReentryExtend",
    kind: "offering",
    i18nKey: "exitReentryExtend",
    href: offeringHref("passports", "tamdid-khuroj-wa-awda"),
    hubs: ["خروج", "تمديد"],
    aliases: ["تمديد خروج وعودة", "تمديد الخروج والعودة", "extend exit reentry"],
    platforms: ["absher"],
    related: [{ id: "offering-exitReentryIssue", strength: "strong" }],
    priority: 82,
    tier: "A",
  },
  {
    id: "offering-finalExit",
    kind: "offering",
    i18nKey: "finalExit",
    href: offeringHref("passports", "khuroj-nihai"),
    hubs: ["خروج", "عامل"],
    aliases: ["خروج نهائي", "تاشيرة خروج نهائي", "final exit"],
    platforms: ["absher"],
    related: [{ id: "offering-exitReentryIssue", strength: "medium" }],
    priority: 85,
    tier: "A",
  },
  {
    id: "offering-familyVisitVisa",
    kind: "offering",
    i18nKey: "familyVisitVisa",
    href: offeringHref("passports", "tashirat-ziyara-ailiya"),
    hubs: ["تاشيرة", "زيارة"],
    aliases: ["تاشيرة زيارة عائلية", "زيارة عائلية", "family visit visa"],
    platforms: ["absher"],
    priority: 84,
    tier: "A",
  },
  {
    id: "offering-touristVisitVisa",
    kind: "offering",
    i18nKey: "touristVisitVisa",
    href: offeringHref("passports", "tashirat-ziyara-siyahiya"),
    hubs: ["تاشيرة", "زيارة"],
    aliases: ["تاشيرة سياحية", "زيارة سياحية", "tourist visa"],
    platforms: ["absher"],
    priority: 76,
    tier: "B",
  },
  {
    id: "offering-domesticVisa",
    kind: "offering",
    i18nKey: "domesticVisa",
    href: offeringHref("passports", "tashirat-amala-manziliya"),
    hubs: ["تاشيرة", "عامل"],
    aliases: [
      "عمالة منزلية",
      "تاشيرة عمالة منزلية",
      "خادمة",
      "مساند",
      "domestic worker",
      "musaned",
    ],
    platforms: ["musaned"],
    priority: 86,
    tier: "A",
  },
  {
    id: "offering-consulateAppointment",
    kind: "offering",
    i18nKey: "consulateAppointment",
    href: offeringHref("passports", "mawid-qunsuliya"),
    hubs: ["موعد", "توثيق"],
    aliases: ["موعد قنصلية", "حجز قنصلية", "consulate appointment"],
    priority: 55,
    tier: "C",
  },
  {
    id: "offering-workVisaPermanent",
    kind: "offering",
    i18nKey: "workVisaPermanent",
    href: offeringHref("labor", "tashirat-amal-daim"),
    hubs: ["تاشيرة", "عامل", "عقد"],
    aliases: ["تاشيرة عمل", "تاشيرة عمل دائم", "استقدام", "work visa", "qiwa visa"],
    platforms: ["qiwa"],
    related: [
      { id: "offering-workVisaTemporary", strength: "strong" },
      { id: "offering-transferSponsorship", strength: "medium" },
    ],
    priority: 90,
    tier: "S",
  },
  {
    id: "offering-workVisaTemporary",
    kind: "offering",
    i18nKey: "workVisaTemporary",
    href: offeringHref("labor", "tashirat-amal-muwaqqat"),
    hubs: ["تاشيرة", "عامل"],
    aliases: ["تاشيرة عمل مؤقت", "عمل مؤقت", "temporary work visa"],
    platforms: ["qiwa"],
    priority: 78,
    tier: "A",
  },
  {
    id: "offering-dropAbscondedWorker",
    kind: "offering",
    i18nKey: "dropAbscondedWorker",
    href: offeringHref("labor", "isqat-amil-kharaj"),
    hubs: ["عامل", "كفالة"],
    aliases: ["بلاغ هروب", "اسقاط عامل", "هروب عامل", "absconding", "runaway worker"],
    platforms: ["absher"],
    priority: 74,
    tier: "A",
  },
  {
    id: "offering-ajeerContract",
    kind: "offering",
    i18nKey: "ajeerContract",
    href: offeringHref("labor", "aqd-ajeer"),
    hubs: ["عقد", "عامل"],
    aliases: ["عقد اجير", "اجير", "ajeer contract"],
    platforms: ["ajeer", "qiwa"],
    priority: 73,
    tier: "A",
  },
  {
    id: "offering-changeProfession",
    kind: "offering",
    i18nKey: "changeProfession",
    href: offeringHref("labor", "tadil-mihna"),
    hubs: ["مهنة", "عامل", "تعديل"],
    aliases: [
      "تعديل مهنة",
      "تغيير مهنة",
      "ابغى اغير مهنة",
      "change profession",
      "job title change",
    ],
    platforms: ["qiwa", "absher"],
    related: [
      { id: "offering-transferSponsorship", strength: "strong" },
      { id: "offering-workerIqamaRenew", strength: "medium" },
    ],
    priority: 88,
    tier: "S",
  },
  {
    id: "offering-mudadWagesFile",
    kind: "offering",
    i18nKey: "mudadWagesFile",
    href: offeringHref("labor", "raf-milaff-mudad"),
    hubs: ["اجور", "موظف", "مدد"],
    aliases: ["مدد", "حماية اجور", "رفع ملف اجور", "mudad", "wage protection"],
    platforms: ["mudad"],
    priority: 77,
    tier: "A",
  },
  {
    id: "offering-openCr",
    kind: "offering",
    i18nKey: "openCr",
    href: offeringHref("commerce", "fath-sijill-tijari"),
    hubs: ["سجل", "منشأة", "اصدار"],
    aliases: [
      "فتح سجل تجاري",
      "استخراج سجل تجاري",
      "تأسيس شركة",
      "سجل جديد",
      "open commercial registration",
      "new cr",
    ],
    platforms: ["commerce", "businessCenter"],
    related: [
      { id: "offering-reserveTradeName", strength: "strong" },
      { id: "offering-municipalLicense", strength: "medium" },
      { id: "offering-chamberMembership", strength: "medium" },
    ],
    intents: ["transactional", "commercial"],
    priority: 96,
    tier: "S",
  },
  {
    id: "offering-renewCr",
    kind: "offering",
    i18nKey: "renewCr",
    href: offeringHref("commerce", "tajdid-sijill-tijari"),
    hubs: ["سجل", "تجديد"],
    aliases: ["تجديد سجل تجاري", "تجديد السجل", "renew cr", "cr renewal"],
    platforms: ["commerce"],
    related: [{ id: "offering-openCr", strength: "medium" }],
    priority: 91,
    tier: "S",
  },
  {
    id: "offering-addActivity",
    kind: "offering",
    i18nKey: "addActivity",
    href: offeringHref("commerce", "idafa-nashat"),
    hubs: ["سجل", "رخصة"],
    aliases: ["اضافة نشاط", "نشاط تجاري", "add activity"],
    platforms: ["commerce"],
    priority: 70,
    tier: "B",
  },
  {
    id: "offering-reserveTradeName",
    kind: "offering",
    i18nKey: "reserveTradeName",
    href: offeringHref("commerce", "hajz-ism-tijari"),
    hubs: ["سجل", "اصدار"],
    aliases: ["حجز اسم تجاري", "اسم تجاري", "trade name"],
    platforms: ["commerce"],
    related: [{ id: "offering-openCr", strength: "strong" }],
    priority: 72,
    tier: "A",
  },
  {
    id: "offering-cancelCr",
    kind: "offering",
    i18nKey: "cancelCr",
    href: offeringHref("commerce", "shatb-sijill-muassasat"),
    hubs: ["سجل", "الغاء"],
    aliases: ["شطب سجل", "الغاء سجل تجاري", "cancel cr"],
    platforms: ["commerce"],
    priority: 68,
    tier: "B",
  },
  {
    id: "offering-transferCrOwnership",
    kind: "offering",
    i18nKey: "transferCrOwnership",
    href: offeringHref("commerce", "naql-milkiyat-sijill"),
    hubs: ["نقل", "سجل", "ملكية"],
    aliases: [
      "نقل ملكية سجل",
      "نقل سجل تجاري",
      "نقل ملكية منشأة",
      "transfer cr ownership",
    ],
    platforms: ["commerce"],
    related: [
      { id: "offering-transferActivityLicense", strength: "strong" },
      { id: "offering-transferSponsorship", strength: "weak" },
    ],
    priority: 87,
    tier: "A",
  },
  {
    id: "offering-transferActivityLicense",
    kind: "offering",
    i18nKey: "transferActivityLicense",
    href: offeringHref("commerce", "naql-rukhsa-nashat"),
    hubs: ["نقل", "رخصة"],
    aliases: ["نقل ترخيص", "نقل رخصة نشاط", "transfer license"],
    platforms: ["commerce"],
    priority: 71,
    tier: "B",
  },
  {
    id: "offering-chamberMembership",
    kind: "offering",
    i18nKey: "chamberMembership",
    href: offeringHref("commerce", "ishtirak-ghurfa"),
    hubs: ["منشأة", "تصديق"],
    aliases: ["غرفة تجارية", "اشتراك الغرفة", "chamber membership"],
    priority: 64,
    tier: "B",
  },
  {
    id: "offering-chamberAttestation",
    kind: "offering",
    i18nKey: "chamberAttestation",
    href: offeringHref("commerce", "tasdiq-ghurfa"),
    hubs: ["تصديق"],
    aliases: ["تصديق غرفة", "تصديق الغرفة التجارية", "chamber attestation"],
    priority: 66,
    tier: "B",
  },
  {
    id: "offering-mofaAttestation",
    kind: "offering",
    i18nKey: "mofaAttestation",
    href: offeringHref("commerce", "tawthiq-kharijiya"),
    hubs: ["تصديق", "توثيق"],
    aliases: ["توثيق خارجية", "تصديق وزارة الخارجية", "mofa attestation"],
    priority: 67,
    tier: "B",
  },
  {
    id: "offering-mediaLicense",
    kind: "offering",
    i18nKey: "mediaLicense",
    href: offeringHref("commerce", "tarkhis-ilam"),
    hubs: ["رخصة"],
    aliases: ["ترخيص اعلامي", "media license"],
    priority: 50,
    tier: "C",
  },
  {
    id: "offering-municipalLicense",
    kind: "offering",
    i18nKey: "municipalLicense",
    href: offeringHref("municipal", "rukhsa-baladiya"),
    hubs: ["رخصة", "بلدي", "منشأة"],
    aliases: ["رخصة بلدية", "رخصة بلدي", "municipal license", "balady license"],
    platforms: ["balady"],
    related: [
      { id: "offering-safetyLicense", strength: "strong" },
      { id: "offering-openCr", strength: "medium" },
    ],
    priority: 89,
    tier: "S",
  },
  {
    id: "offering-wasteContract",
    kind: "offering",
    i18nKey: "wasteContract",
    href: offeringHref("municipal", "aqd-nifayat"),
    hubs: ["عقد", "بلدي"],
    aliases: ["عقد نفايات", "نفايات", "waste contract"],
    platforms: ["balady"],
    priority: 52,
    tier: "C",
  },
  {
    id: "offering-safetyLicense",
    kind: "offering",
    i18nKey: "safetyLicense",
    href: offeringHref("civilDefense", "tarkhis-salama"),
    hubs: ["رخصة", "سلامة"],
    aliases: ["ترخيص سلامة", "دفاع مدني", "safety license"],
    related: [{ id: "offering-municipalLicense", strength: "strong" }],
    priority: 79,
    tier: "A",
  },
  {
    id: "offering-sfdaLicense",
    kind: "offering",
    i18nKey: "sfdaLicense",
    href: offeringHref("health", "tarkhis-hayat-dawa"),
    hubs: ["رخصة", "صحة"],
    aliases: ["ترخيص هيئة الغذاء", "سفدا", "sfda"],
    priority: 61,
    tier: "B",
  },
  {
    id: "offering-trafficAppointment",
    kind: "offering",
    i18nKey: "trafficAppointment",
    href: offeringHref("traffic", "mawid-murur"),
    hubs: ["سيارة", "موعد", "مرور"],
    aliases: ["موعد مرور", "حجز مرور", "traffic appointment"],
    platforms: ["absher"],
    priority: 63,
    tier: "B",
  },
  {
    id: "offering-najizAppointment",
    kind: "offering",
    i18nKey: "najizAppointment",
    href: offeringHref("najiz", "hajz-najiz-tasahil"),
    hubs: ["ناجز", "موعد", "توثيق", "وكالة"],
    aliases: ["موعد ناجز", "حجز ناجز", "najiz appointment"],
    platforms: ["najiz"],
    priority: 81,
    tier: "A",
  },
  {
    id: "offering-socialInsuranceReg",
    kind: "offering",
    i18nKey: "socialInsuranceReg",
    href: offeringHref("gosi", "tasjil-daman-ijtimaei"),
    hubs: ["تامين", "موظف", "منشأة"],
    aliases: ["تسجيل تامينات", "تامينات اجتماعية", "gosi registration"],
    platforms: ["gosi"],
    priority: 76,
    tier: "A",
  },
  {
    id: "offering-noorRegistration",
    kind: "offering",
    i18nKey: "noorRegistration",
    href: offeringHref("civilStatus", "tasjil-noor"),
    hubs: ["تسجيل"],
    aliases: ["تسجيل نور", "نظام نور", "noor registration"],
    priority: 48,
    tier: "C",
  },
  {
    id: "offering-citizenAccount",
    kind: "offering",
    i18nKey: "citizenAccount",
    href: offeringHref("civilStatus", "hisab-almuwatin"),
    hubs: ["مواطن"],
    aliases: ["حساب المواطن", "citizen account"],
    priority: 54,
    tier: "C",
  },
  {
    id: "offering-vatFiling",
    kind: "offering",
    i18nKey: "vatFiling",
    href: offeringHref("zakat", "raf-daribat-qima"),
    hubs: ["ضريبة", "زكاة"],
    aliases: [
      "ضريبة القيمة المضافة",
      "رفع اقرار ضريبي",
      "ضريبة",
      "vat filing",
      "vat return",
    ],
    platforms: ["zakat"],
    priority: 83,
    tier: "A",
  },

  // —— Tech ——
  ...Object.entries(TECH_SLUGS).map(([key, slug]) => ({
    id: `tech-${key}`,
    kind: "tech" as const,
    i18nKey: key,
    href: `/services/tech/${slug}`,
    hubs: ["تقني", "موقع", "تطبيق"],
    aliases: techAliases(key),
    priority: 45,
    tier: "B" as const,
  })),
];

function techAliases(key: string): string[] {
  const map: Record<string, string[]> = {
    websites: ["تصميم مواقع", "عمل موقع", "website", "web design"],
    mobile: ["تطبيق جوال", "تطبيق موبايل", "mobile app"],
    maps: ["خرائط", "قوقل ماب", "google maps"],
    marketing: ["تسويق", "اعلانات", "marketing", "ads"],
    automation: ["اتمتة", "اوتومايشن", "automation", "n8n"],
    support: ["دعم فني", "technical support"],
    ai: ["ذكاء اصطناعي", "ai", "chatgpt"],
    data: ["بيانات", "تحليل بيانات", "data"],
    cloud: ["سحابة", "كلاود", "cloud"],
  };
  return map[key] || [key];
}

/** Ensure every gov offering in GOV_OFFERINGS has a catalog node */
export function assertCatalogCoverage(): string[] {
  const missing: string[] = [];
  for (const o of GOV_OFFERINGS) {
    if (!SEARCH_CATALOG.some((n) => n.id === `offering-${o.key}`)) {
      missing.push(o.key);
    }
  }
  return missing;
}

export const HUB_DISAMBIGUATION: Record<
  string,
  { labelKey: string; hint: string; hubs: string[] }[]
> = {
  نقل: [
    {
      labelKey: "disambiguate.transferSponsorship",
      hint: "نقل كفالة / نقل خدمات عامل",
      hubs: ["نقل", "كفالة", "عامل"],
    },
    {
      labelKey: "disambiguate.transferCr",
      hint: "نقل ملكية سجل تجاري",
      hubs: ["نقل", "سجل", "ملكية"],
    },
    {
      labelKey: "disambiguate.transferLicense",
      hint: "نقل ترخيص نشاط",
      hubs: ["نقل", "رخصة"],
    },
    {
      labelKey: "disambiguate.traffic",
      hint: "خدمات مرور / مركبات",
      hubs: ["نقل", "سيارة", "مرور"],
    },
  ],
  كفالة: [
    {
      labelKey: "disambiguate.transferSponsorship",
      hint: "نقل كفالة",
      hubs: ["نقل", "كفالة"],
    },
    {
      labelKey: "disambiguate.labor",
      hint: "خدمات عمالة وكفالات",
      hubs: ["كفالة", "عامل"],
    },
  ],
  عامل: [
    {
      labelKey: "disambiguate.transferSponsorship",
      hint: "نقل خدمات عامل",
      hubs: ["نقل", "عامل"],
    },
    {
      labelKey: "disambiguate.iqama",
      hint: "تجديد إقامة عامل",
      hubs: ["اقامة", "عامل"],
    },
    {
      labelKey: "disambiguate.exit",
      hint: "خروج وعودة / خروج نهائي",
      hubs: ["خروج", "عامل"],
    },
    {
      labelKey: "disambiguate.profession",
      hint: "تعديل مهنة",
      hubs: ["مهنة", "عامل"],
    },
  ],
};

export function getNodeById(id: string): SearchNode | undefined {
  return SEARCH_CATALOG.find((n) => n.id === id);
}
